version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: "deal_postgres"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deal_db
    restart: always
  rabbitmq:
    image: rabbitmq:3.13.6-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  db_data: